apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: guestbook
spec:
  host: guestbook.apps.cluster-4464g.4464g.sandbox1056.opentlc.com
  port:
    targetPort: 80
  to:
    kind: Service
    name: guestbook
    weight: 100
